### ISSUE TITLE
Missing Js file to Project

### ISSUE THREAD

**Issue by 0xBiriyani** [Dovly/MyApp#1]
@Dovly 
Create a Js and Add it our repo

**Comment by Dovly** [comment]
@naveenpothana  ok i wiil

**Comment by 0xBiriyani** [comment]
@Dovly  
Ok, Please do it asap

**Comment by Dovly** [comment]
@naveenpothana  
i have added js file in this commit id b07dc78d2b73878ce8949daee41f93082299f014
